* The Ultimate Charm
Once upon a time, in a fairytale kingdom far, far away, some dwarves learned to make magical charms. These charms were made from gems and machinery and a dwarvish sort of magic. These charms came in many forms: some useful, some entertaining, some simply interesting to look at and contemplate. The dwarves were rather pleased with these charms that they were making, and they showed their creations with each other and were quite happy building, showing and sharing.

Soon some of the men and women of the kingdom saw some of the charms. At first, they seemed to the people rather odd and dwarvish, but some of the men and women, those most clever in trading, saw great potential in the charms. A few of these decided to approach the dwarves with an offer.

"You dwarves are awfully clever to make these charms," they said. "But we know how you dwarves are much more interested in craftsmanship than in trade. Why not team up with us? You can build charms and we can trade them for gold and other things, and we'll all become rich!"

This was appealing to many of the dwarves, who liked gold as much as anyone else. Some of the dwarves, purists who already had all the wealth that they needed, spoke with much pomp and principle about how the men and women would corrupt the charms with all of this trade and gold, but it was easy for them to say that. Other dwarves who enjoyed the hobby of making charms heeded these warnings but also wanted to use their craft to make a comfortable life for their families. And others still were terribly excited by the prospect of great wealth and did not entertain the purists' warnings. And so many went to work with the men and women.

Sure enough, in no time at all, trade was roaring. The other people of the kingdom soon saw the value of the charms, sometimes even to the point of obsession! They became part of the fabric of life. The clever men and women and the dwarves made a lot of gold. For the most part, everyone was happy with the arrangement, except the purist dwarves who would tut and shake their heads.

Not everything was perfect though. The clever men and women had particular ways of working which were not always a perfect match for the dwarves. The dwarves liked to play and experiment and share their work, especially with other dwarves who were interested in how the charms worked. The clever men and women wanted to have a more systematic approach: they devised schemes to maximise the number of charms made and the superficial sparkliness of them (which undeniably helped with trade), even when it meant cutting corners on the actual quality.

"You dwarves are excellent craftsmen," they said, "but we know what the other people of the kingdom really want. Let us do the boring stuff like plan the work and draw up designs for how the charms should work, and then you can not be distracted from your happy craft." And the dwarves, who liked the sound of avoiding chores and having more time for craft, grumbled a bit but ultimately agreed.

Eventually, the clever men and women had a brainwave. How about the dwarves build a charm-building charm! That way everything could be much more efficient, and they wouldn't have to deal with the curmudgeonly dwarves so much (which was sometimes quite difficult).

Of course, this idea was nothing new to the dwarves. In fact, the charm-building process was by then rather complicated, involving many layers of charms building charms building charms. But now this idea really captured the imagination of the clever men and women, and so they asked the dwarves to make it.

"The charm-building charm should speak the language of us clever men and women; we don't want to have to learn dwarvish to instruct it!" the clever men and women said. The dwarves knew this would be a bit of a problem because they had learned, through much trial and error, how to translate the wishes of the clever men and women into dwarvish concepts with which they could make charms. They knew that, to some extent, it was the magic of the charms that had shaped the wishes of the people of the kingdom, rather than vice versa.

This was a bit of a pickle, and so the dwarves called a Great Council. For 1,024 days and nights they stayed locked in the workshop, debating, designing, arguing and creating the ultimate charm-building charm for the clever men and women to sell.

On the morning of the 1,025th day, the clever men and women (who were fed up with waiting) went to the workshop to see what was going on. They found it empty of dwarves, all the tools gone, no mess (which was very unusual), nothing... except a great chest in the middle of the workshop. The cleverest of the clever men and women stepped forward and opened the chest and reached inside and drew from it a perfectly circular mirror.
